service: conyappa

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3

functions:
  chooseResult:
    handler: src.choose_result
    description: Sends a POST request to /draws.

  createDraw:
    handler: src.create_draw
    description: Sends a POST request to /draws.

  randomSeed:
    handler: src.random_seed
    description: Returns a string of discernible origins to be used as seed for random generators.
