service: conyappa

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3

functions:
  createDraw:
    handler: src/create_draw.main
    description: Sends a POST request to /draw.

  randomSeed:
    handler: src/random_seed.main
    description: Returns a string of discernible origins to be used as seed for random generators.
