service: conyappa

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3

functions:
  randomSeed:
    handler: src/random_seed.main
    description: Generates a random string to be used as seed.
