name: checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up virtual environment
        run: make createvenv

      - name: Lint with Black
        run: poetry run black src --check

      - name: Lint with Flake8
        run: poetry run flake8 src

      - name: Lint with iSort
        run: poetry run isort src --check
